name: pdf_viewer_v2
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.0
homepage: https://github.com/khangpt/pdf_viewer_v2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  numberpicker: ^2.1.1
  path_provider: ^2.0.8

dev_dependencies:
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
